### ISSUE TITLE
error parsing nmco from chrometrics github

### ISSUE THREAD

**Issue by QuyANgo** [GVS-Lab/germinal_center#1]
Hello,

I would like to try your code on my imaging data. 

I git-cloned germinal-center and tried to create the conda environment gc:
conda create --name gc --file germinal_center/requirements.txt

but I got this error:
CondaValueError: could not parse 'nmco @ git+https://github.com/GVS-Lab/chrometrics.git' in: germinal_center/requirements.txt

Could you please let me know how I can fix this problem?

Thank you very much!

**Comment by dpaysan** [comment]
Please try installing the package via 

conda create -n gc python=3.8
conda activate gc
pip install -r requirements.txt

**Comment by dpaysan** [comment]
Closing issue here
