### ISSUE TITLE
package versions have conflicting dependencies

### ISSUE THREAD

**Issue by QuyANgo** [GVS-Lab/germinal_center#2]
Hello,

I added python=3.8 when creating the conda environment as you suggested in the first issue.

Now I've got error about dependency conflicts of package versions:

_The user requested numpy~=1.20.0
    csbdeep 0.6.3 depends on numpy
    h5py 2.10.0 depends on numpy>=1.7
    imageio 2.9.0 depends on numpy
    keras-preprocessing 1.1.2 depends on numpy>=1.9.1
    matplotlib 3.3.4 depends on numpy>=1.15
    numba 0.54.0 depends on numpy<1.21 and >=1.17
    opencv-python 4.5.3.56 depends on numpy>=1.17.3
    opencv-python-headless 4.5.1.48 depends on numpy>=1.17.3
    opt-einsum 3.3.0 depends on numpy>=1.7
    pandas 1.3.3 depends on numpy>=1.17.3
    pywavelets 1.1.1 depends on numpy>=1.13.3
    scipy 1.4.1 depends on numpy>=1.13.3
    seaborn 0.11.2 depends on numpy>=1.15
    tensorboard 2.6.0 depends on numpy>=1.12.0
    tifffile 2021.2.26 depends on numpy>=1.15.1
    umap-learn 0.5.1 depends on numpy>=1.17
    scikit-image 0.19.2 depends on numpy>=1.17.0
    scikit-learn 1.1.1 depends on numpy>=1.17.3
    tensorflow 2.3.0 depends on numpy<1.19.0 and >=1.16.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts_

I see that the numpy versions for keras-preprocessing and tensorflow are in conflict. I tried a few different version of tensorflow (2.6.0 and 2.13.0) for requirements.txt, but the conflict appeared in another package (absl-py).

Could you please check the compatibility of all versions in the requirements.txt?

Many thanks!

**Comment by dpaysan** [comment]
[requirements.txt](https://github.com/user-attachments/files/18066598/requirements.txt)

Please try installing the dependencies using the attached requirements.txt file and python v3.8.13. I have just tested the installation and validated that it completes without any errors. Please note that some conflicts might be caused due to changes in the installed site-packages that could lead to compatibility issues like .e.g in hdbscan, which is somewhat outside of our control. We nonetheless apologize for the inconvenience.

**Comment by QuyANgo** [comment]
Dear Daniel,

Thanks a lot for this file. Now I can install gc without problems. In the
next few days I'll run the code in your notebooks.

Will you publish your work that uses gc soon? I'd love to read your paper.

Best,
Quy

Quy A. Ngo

**Comment by dpaysan** [comment]
Glad I could help. The paper is still under review. Hopefully it will be out soon. I'll update the ReadMe once it is.

All the best!
